import type { Preset } from "./types";

export const assembleiaDeDeus: Preset = {
  id: "assembleia-de-deus",
  label: "Assembleia de Deus",
  description:
    "Estrutura campo → setor → congregação, EBD trimestral, cargos de obreiros e categorias financeiras com repasse à sede.",
  vocabulary: {
    church: "Ministério",
    campus: "Congregação",
    campusPlural: "Congregações",
    sede: "Igreja Sede",
    campusLeader: "Dirigente",
    member: "Membro",
    memberPlural: "Membros",
    memberRoll: "Rol de membros",
    smallGroup: "Célula",
    smallGroupPlural: "Células",
    ministry: "Departamento",
    ministryPlural: "Departamentos",
    tithe: "Dízimo",
    offering: "Oferta",
    sundaySchool: "EBD",
    worker: "Obreiro",
    workerPlural: "Obreiros",
  },
  offices: [
    { key: "auxiliar", label: "Auxiliar", order: 1 },
    { key: "cooperador", label: "Cooperador(a)", order: 2 },
    { key: "diacono", label: "Diácono / Diaconisa", order: 3 },
    { key: "presbitero", label: "Presbítero", order: 4 },
    { key: "evangelista", label: "Evangelista", order: 5 },
    { key: "pastor", label: "Pastor", order: 6 },
    { key: "missionaria", label: "Missionária", order: 6 },
  ],
  sundaySchoolClasses: [
    { key: "bercario", label: "Berçário", ageMin: 0, ageMax: 2 },
    { key: "maternal", label: "Maternal", ageMin: 3, ageMax: 4 },
    { key: "jardim", label: "Jardim", ageMin: 5, ageMax: 6 },
    { key: "primarios", label: "Primários", ageMin: 7, ageMax: 8 },
    { key: "juniores", label: "Juniores", ageMin: 9, ageMax: 10 },
    { key: "pre_adolescentes", label: "Pré-adolescentes", ageMin: 11, ageMax: 12 },
    { key: "adolescentes", label: "Adolescentes", ageMin: 13, ageMax: 17 },
    { key: "jovens", label: "Jovens", ageMin: 18, ageMax: 30 },
    { key: "adultos", label: "Adultos", ageMin: 31 },
    { key: "novos_convertidos", label: "Novos convertidos" },
    { key: "discipulado", label: "Discipulado" },
  ],
  ministries: [
    "Louvor",
    "Mocidade",
    "Senhoras",
    "Varões",
    "Adolescentes",
    "Crianças",
    "Mídia e Som",
    "Recepção e Diaconia",
    "Missões",
    "Círculo de Oração",
  ],
  serviceTypes: [
    "Culto de Celebração",
    "Culto de Doutrina",
    "Culto de Ensino",
    "Culto de Oração",
    "Santa Ceia",
    "EBD",
    "Círculo de Oração",
    "Culto de Jovens",
    "Culto de Senhoras",
  ],
  financeCategories: [
    { key: "dizimos", label: "Dízimos", kind: "entrada" },
    { key: "ofertas", label: "Ofertas", kind: "entrada" },
    { key: "oferta_missionaria", label: "Oferta missionária", kind: "entrada" },
    { key: "oferta_ebd", label: "Oferta da EBD", kind: "entrada" },
    { key: "campanhas", label: "Campanhas", kind: "entrada" },
    { key: "repasse_recebido", label: "Repasse de congregações", kind: "entrada" },
    { key: "repasse_sede", label: "Repasse à sede", kind: "saida" },
    { key: "pessoal_pastoral", label: "Sustento pastoral", kind: "saida" },
    { key: "agua_luz_telefone", label: "Água, luz e telefone", kind: "saida" },
    { key: "aluguel", label: "Aluguel", kind: "saida" },
    { key: "manutencao", label: "Manutenção e obras", kind: "saida" },
    { key: "missoes", label: "Missões", kind: "saida" },
    { key: "assistencia_social", label: "Assistência social", kind: "saida" },
    { key: "material_ebd", label: "Material de EBD", kind: "saida" },
    { key: "diversos", label: "Diversos", kind: "saida" },
  ],
};
